server:
  port: 8082

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/jobs_db
    username: postgres
    password: postgres
  liquibase:
    change-log: classpath:liquibase/db.changelog.xml

zookeeper:
  host: localhost:2181
  session-timeout: 10_000